const flavorText = [
  "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.",
  "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
  "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
  "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
  "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
  "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
  "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
  "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
  "A brutal POKéMON with pressurized water jets on its shell. They are used for high speed tackles.",
  "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
  "This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
  "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
  "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
  "Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.",
  "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
  "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
  "Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.",
  "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.",
  "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
  "It uses its whis­ kers to maintain its balance. It apparently slows down if they are cut off.",
  "It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.",
  "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
  "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.",
  "It is rumored that the ferocious warning markings on its belly differ from area to area.",
  "When several of these POKéMON gather, their electricity could build and cause lightning storms.",
  "Its long tail serves as a ground to protect itself from its own high-voltage power.",
  "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
  "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.",
  "Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.",
  "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.",
  "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.",
  "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.",
  "An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.",
  "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.",
  "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
  "A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.",
  "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.",
  "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
  "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.",
  "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.",
  "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
  "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
  "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.",
  "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.",
  "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.",
  "Burrows to suck tree roots. The mushrooms on its back grow by draw­ ing nutrients from the bug host.",
  "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.",
  "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.",
  "The dustlike scales covering its wings are color-coded to indicate the kinds of poison it has.",
  "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
  "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
  "It washes its face regularly to keep the coin on its forehead spotless. It doesn’t get along with Galarian Meowth.",
  "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
  "While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers.",
  "Often seen swim­ ming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.",
  "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.",
  "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
  "Very protective of its territory. It will bark and bite to repel intruders from its space.",
  "A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.",
  "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.",
  "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.",
  "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.",
  "Using its ability to read minds, it will identify impending danger and TELEPORT to safety.",
  "It emits special alpha waves from its body that induce headaches just by being close by.",
  "Its brain can out­ perform a super­ computer. Its intelligence quotient is said to be 5,000.",
  "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
  "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.",
  "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.",
  "A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture.",
  "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.",
  "Said to live in huge colonies deep in jungles, although no one has ever returned from there.",
  "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.",
  "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.",
  "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
  "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.",
  "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.",
  "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.",
  "Very competitive, this POKéMON will chase anything that moves fast in the hopes of racing it.",
  "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.",
  "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps.",
  "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves.",
  "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.",
  "The sprig of green onions it holds is its weapon. It is used much like a metal sword.",
  "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.",
  "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.",
  "The protruding horn on its head is very hard. It is used for bashing through thick ice.",
  "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.",
  "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.",
  "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.",
  "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.",
  "When attacked, it launches its horns in quick volleys. Its innards have never been seen.",
  "Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.",
  "Because of its ability to slip through block walls, it is said to be from an­ other dimension.",
  "Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright.",
  "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.",
  "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.",
  "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.",
  "Its pincers are not only powerful weapons, they are used for balance when walking sideways.",
  "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.",
  "Usually found in power plants. Easily mistaken for a POKé BALL, they have zapped many people.",
  "It stores electric energy under very high pressure. It often explodes with little or no provocation.",
  "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.",
  "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.",
  "Because it never removes its skull helmet, no one has ever seen this POKéMON's real face.",
  "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.",
  "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.",
  "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.",
  "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.",
  "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.",
  "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years.",
  "A POKéMON with a one-track mind. Once it charges,  it won't stop running until it falls asleep.",
  "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.",
  "A rare and elusive POKéMON that is said to bring happiness to those who manage to get it.",
  "The whole body is swathed with wide vines that are similar to sea­ weed. Its vines shake as it walks.",
  "The infant rarely ventures out of its mother's protective pouch until it is 3 years old.",
  "Known to shoot down flying bugs with precision blasts of ink from the surface of the water.",
  "Capable of swim­ ming backwards by rapidly flapping its wing-like pectoral fins and stout tail.",
  "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.",
  "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.",
  "If its body is torn, it can grow back if the red core remains. The core flashes at midnight.",
  "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.",
  "If interrupted while it is miming, it will slap around the offender with its broad hands.",
  "With ninja-like agility and speed, it can create the illusion that there is more than one.",
  "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.",
  "Normally found near power plants, they can wander away and cause major blackouts in cities.",
  "Its body always burns with an orange glow that enables it to hide perfectly among flames.",
  "If it fails to crush the victim in its pincers, it will swing it around and toss it hard.",
  "When it targets an enemy, it charges furiously while whipping its body with its long tails.",
  "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.",
  "Once it begins to rampage, a GYARADOS will burn everything down, even in a harsh storm.",
  "A POKéMON that has been over­ hunted almost to extinction. It can ferry people across the water.",
  "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy.",
  "Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs.",
  "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.",
  "It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts.",
  "When storing thermal energy in its body, its temperature could soar to over 1600 degrees.",
  "A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace.",
  "Although long extinct, in rare cases, it can be genetically resurrected from fossils.",
  "A prehistoric POKéMON that died out when its heavy shell made it impossible to catch prey.",
  "A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago.",
  "Its sleek shape is perfect for swim­ ming. It slashes prey with its claws and drains the body fluids.",
  "A Pokémon that roamed the skies in the dinosaur era. Its teeth are like saw blades.",
  "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.",
  "A legendary bird POKéMON that is said to appear to doomed people who are lost in icy mountains.",
  "A legendary bird POKéMON that is said to appear from clouds while dropping enormous lightning bolts.",
  "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.",
  "Long considered a mythical POKéMON until recently when a small colony was found living underwater.",
  "A mystical POKéMON that exudes a gentle aura. Has the ability to change climate conditions.",
  "An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans.",
  "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
  "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."
];

export default flavorText;
